-- 0057_catalogo_moduli : il catalogo dei moduli, da 23 a 88 modelli
--
-- Il catalogo aveva un solo modello per rarita' e categoria: 23 in tutto, e
-- due moduli trovati erano quasi sempre lo stesso. Ora 18 famiglie, ognuna con
-- una funzione precisa e un modello per ogni rarita' (l'occultamento solo dalle
-- tre piu' alte). Sette effetti sono nuovi: tetto dei caccia, interdizione,
-- corazza, schermatura ambientale, elusione, disturbo elettronico, transponder
-- e fabbrica di caccia a bordo. I modelli esistenti mantengono la chiave; alcuni
-- cambiano valori per stare nella progressione della loro famiglia (i moduli
-- gia' posseduti conservano i valori con cui sono stati trovati).

INSERT INTO item_types (ckey, name, category, family, rarity, effects, base_salvage, descr, sort_order) VALUES
  ('w_autocannoni', 'Autocannoni a rotazione', 'weapon', 'cannoni', 'civ', '{"combat_pct":6}', 8, 'Armamento principale: aumenta la potenza di fuoco in ogni scontro.', 0),
  ('w_railgun', 'Railgun a massa', 'weapon', 'cannoni', 'mil', '{"combat_pct":12}', 22, 'Armamento principale: aumenta la potenza di fuoco in ogni scontro.', 1),
  ('w_plasma', 'Lancia al plasma', 'weapon', 'cannoni', 'exp', '{"combat_pct":20}', 60, 'Armamento principale: aumenta la potenza di fuoco in ogni scontro.', 2),
  ('w_disgregatore', 'Disgregatore xeno', 'weapon', 'cannoni', 'xeno', '{"combat_pct":30}', 160, 'Armamento principale: aumenta la potenza di fuoco in ogni scontro.', 3),
  ('w_precursore', 'Proiettore Precursore', 'weapon', 'cannoni', 'precursor', '{"combat_pct":42}', 420, 'Armamento principale: aumenta la potenza di fuoco in ogni scontro.', 4),
  ('w_rastrelliera', 'Rastrelliera di caccia', 'weapon', 'hangar', 'civ', '{"max_fighters_pct":10}', 8, 'Spazio per più caccia: alza il tetto di caccia che la nave può portare.', 100),
  ('w_hangar', 'Hangar modulare', 'weapon', 'hangar', 'mil', '{"max_fighters_pct":20}', 22, 'Spazio per più caccia: alza il tetto di caccia che la nave può portare.', 101),
  ('w_baia', 'Baia di lancio rapido', 'weapon', 'hangar', 'exp', '{"max_fighters_pct":32}', 60, 'Spazio per più caccia: alza il tetto di caccia che la nave può portare.', 102),
  ('w_nido', 'Nido sciame xeno', 'weapon', 'hangar', 'xeno', '{"max_fighters_pct":45}', 160, 'Spazio per più caccia: alza il tetto di caccia che la nave può portare.', 103),
  ('w_matrice', 'Matrice di forgiatura Precursore', 'weapon', 'hangar', 'precursor', '{"max_fighters_pct":60}', 420, 'Spazio per più caccia: alza il tetto di caccia che la nave può portare.', 104),
  ('w_rampino', 'Rampino gravitazionale', 'weapon', 'interdizione', 'civ', '{"interdict_pct":15}', 8, 'Trattiene il bersaglio: un mercantile sotto tiro fatica a fuggire.', 200),
  ('w_interdittore', 'Proiettore d\'interdizione', 'weapon', 'interdizione', 'mil', '{"interdict_pct":25}', 22, 'Trattiene il bersaglio: un mercantile sotto tiro fatica a fuggire.', 201),
  ('w_ancoraggio', 'Campo di ancoraggio', 'weapon', 'interdizione', 'exp', '{"interdict_pct":40}', 60, 'Trattiene il bersaglio: un mercantile sotto tiro fatica a fuggire.', 202),
  ('w_tela', 'Tela gravitica xeno', 'weapon', 'interdizione', 'xeno', '{"interdict_pct":60}', 160, 'Trattiene il bersaglio: un mercantile sotto tiro fatica a fuggire.', 203),
  ('w_ancora', 'Ancora del Vuoto', 'weapon', 'interdizione', 'precursor', '{"interdict_pct":85,"combat_pct":5}', 420, 'Trattiene il bersaglio: un mercantile sotto tiro fatica a fuggire.', 204),
  ('d_piastre', 'Piastre balistiche', 'defense', 'scudi', 'civ', '{"max_shields_pct":12}', 8, 'Capacità degli scudi: alza il tetto degli scudi della nave.', 300),
  ('d_doppiafase', 'Generatore a doppia fase', 'defense', 'scudi', 'mil', '{"max_shields_pct":18}', 22, 'Capacità degli scudi: alza il tetto degli scudi della nave.', 301),
  ('d_stratificata', 'Matrice di scudi stratificata', 'defense', 'scudi', 'exp', '{"max_shields_pct":26}', 60, 'Capacità degli scudi: alza il tetto degli scudi della nave.', 302),
  ('d_barriera', 'Barriera xeno', 'defense', 'scudi', 'xeno', '{"max_shields_pct":35,"shield_regen":40}', 160, 'Capacità degli scudi: alza il tetto degli scudi della nave.', 303),
  ('d_guscio', 'Guscio di Precursore', 'defense', 'scudi', 'precursor', '{"max_shields_pct":48,"shield_regen":40}', 420, 'Capacità degli scudi: alza il tetto degli scudi della nave.', 304),
  ('d_condensatori', 'Condensatori di ricarica', 'defense', 'rigenerazione', 'civ', '{"shield_regen":30}', 8, 'Ricarica gli scudi a ogni salto di warp.', 400),
  ('d_ondulati', 'Scudi ondulati', 'defense', 'rigenerazione', 'mil', '{"shield_regen":60}', 22, 'Ricarica gli scudi a ogni salto di warp.', 401),
  ('d_cascata', 'Rigeneratore a cascata', 'defense', 'rigenerazione', 'exp', '{"shield_regen":90}', 60, 'Ricarica gli scudi a ogni salto di warp.', 402),
  ('d_simbionte', 'Simbionte ricostruttore', 'defense', 'rigenerazione', 'xeno', '{"shield_regen":120}', 160, 'Ricarica gli scudi a ogni salto di warp.', 403),
  ('d_egida', 'Egida Precursore', 'defense', 'rigenerazione', 'precursor', '{"shield_regen":150,"max_shields_pct":25}', 420, 'Ricarica gli scudi a ogni salto di warp.', 404),
  ('d_prua', 'Deflettore di prua', 'defense', 'deflettori', 'civ', '{"combat_pct":3,"max_shields_pct":5}', 8, 'Un po\' di attacco e un po\' di scudi: il compromesso di chi non sceglie.', 500),
  ('d_tattico', 'Deflettore tattico', 'defense', 'deflettori', 'mil', '{"combat_pct":5,"max_shields_pct":7}', 22, 'Un po\' di attacco e un po\' di scudi: il compromesso di chi non sceglie.', 501),
  ('d_deflettore', 'Deflettore adattivo', 'defense', 'deflettori', 'exp', '{"combat_pct":8,"max_shields_pct":10}', 60, 'Un po\' di attacco e un po\' di scudi: il compromesso di chi non sceglie.', 502),
  ('d_fase', 'Deflettore a fase xeno', 'defense', 'deflettori', 'xeno', '{"combat_pct":11,"max_shields_pct":14}', 160, 'Un po\' di attacco e un po\' di scudi: il compromesso di chi non sceglie.', 503),
  ('d_assoluto', 'Deflettore Precursore', 'defense', 'deflettori', 'precursor', '{"combat_pct":15,"max_shields_pct":18}', 420, 'Un po\' di attacco e un po\' di scudi: il compromesso di chi non sceglie.', 504),
  ('d_ablative', 'Piastre ablative', 'defense', 'corazza', 'civ', '{"armor_pct":4}', 8, 'Corazzatura: ogni colpo ricevuto fa meno danni, da chiunque arrivi.', 600),
  ('d_reattiva', 'Corazza reattiva', 'defense', 'corazza', 'mil', '{"armor_pct":7}', 22, 'Corazzatura: ogni colpo ricevuto fa meno danni, da chiunque arrivi.', 601),
  ('d_memoria', 'Lega a memoria di forma', 'defense', 'corazza', 'exp', '{"armor_pct":11}', 60, 'Corazzatura: ogni colpo ricevuto fa meno danni, da chiunque arrivi.', 602),
  ('d_carapace', 'Carapace xeno', 'defense', 'corazza', 'xeno', '{"armor_pct":16}', 160, 'Corazzatura: ogni colpo ricevuto fa meno danni, da chiunque arrivi.', 603),
  ('d_neutronio', 'Pelle di neutronio', 'defense', 'corazza', 'precursor', '{"armor_pct":22}', 420, 'Corazzatura: ogni colpo ricevuto fa meno danni, da chiunque arrivi.', 604),
  ('d_radiazioni', 'Schermatura anti-radiazioni', 'defense', 'schermi', 'civ', '{"hazard_resist_pct":20}', 8, 'Protegge da mine, cannoni Quasar e pericoli ambientali all\'ingresso.', 700),
  ('d_stagni', 'Paratie stagne', 'defense', 'schermi', 'mil', '{"hazard_resist_pct":35}', 22, 'Protegge da mine, cannoni Quasar e pericoli ambientali all\'ingresso.', 701),
  ('d_dissipatore', 'Dissipatore ionico', 'defense', 'schermi', 'exp', '{"hazard_resist_pct":50}', 60, 'Protegge da mine, cannoni Quasar e pericoli ambientali all\'ingresso.', 702),
  ('d_membrana', 'Membrana xeno', 'defense', 'schermi', 'xeno', '{"hazard_resist_pct":70}', 160, 'Protegge da mine, cannoni Quasar e pericoli ambientali all\'ingresso.', 703),
  ('d_velo', 'Velo Precursore', 'defense', 'schermi', 'precursor', '{"hazard_resist_pct":90}', 420, 'Protegge da mine, cannoni Quasar e pericoli ambientali all\'ingresso.', 704),
  ('v_iniettori', 'Iniettori tarati', 'drive', 'propulsori', 'civ', '{"warp_turn_reduction":1}', 8, 'Salti di warp più economici in turni.', 800),
  ('v_bobine', 'Bobine warp potenziate', 'drive', 'propulsori', 'mil', '{"warp_turn_reduction":1}', 22, 'Salti di warp più economici in turni.', 801),
  ('v_transwarp', 'Nucleo transwarp', 'drive', 'propulsori', 'exp', '{"warp_turn_reduction":1,"combat_pct":4}', 60, 'Salti di warp più economici in turni.', 802),
  ('v_motore_xeno', 'Motore a curvatura xeno', 'drive', 'propulsori', 'xeno', '{"warp_turn_reduction":1,"combat_pct":10}', 160, 'Salti di warp più economici in turni.', 803),
  ('v_precursore', 'Motore di Precursore', 'drive', 'propulsori', 'precursor', '{"warp_turn_reduction":2,"combat_pct":8}', 420, 'Salti di warp più economici in turni.', 804),
  ('v_ugelli', 'Ugelli di manovra', 'drive', 'manovra', 'civ', '{"evade_pct":6}', 8, 'Elusione: a volte gli ostili non riescono ad agganciarti.', 900),
  ('v_vettoriali', 'Propulsori vettoriali', 'drive', 'manovra', 'mil', '{"evade_pct":10}', 22, 'Elusione: a volte gli ostili non riescono ad agganciarti.', 901),
  ('v_sfasati', 'Motore a impulsi sfasati', 'drive', 'manovra', 'exp', '{"evade_pct":15}', 60, 'Elusione: a volte gli ostili non riescono ad agganciarti.', 902),
  ('v_pinne', 'Pinne gravitiche xeno', 'drive', 'manovra', 'xeno', '{"evade_pct":22}', 160, 'Elusione: a volte gli ostili non riescono ad agganciarti.', 903),
  ('v_fantasma', 'Passo del fantasma', 'drive', 'manovra', 'precursor', '{"evade_pct":30}', 420, 'Elusione: a volte gli ostili non riescono ad agganciarti.', 904),
  ('c_scanner_denso', 'Scanner di densità', 'computer', 'sensori', 'civ', '{"scanner":"density"}', 8, 'Scanner e raggio di scansione.', 1000),
  ('c_oloscanner', 'Olo-scanner', 'computer', 'sensori', 'mil', '{"scanner":"holo","scan_range":1}', 22, 'Scanner e raggio di scansione.', 1001),
  ('c_lungoraggio', 'Matrice di sensori a lungo raggio', 'computer', 'sensori', 'exp', '{"scanner":"holo","scan_range":2}', 60, 'Scanner e raggio di scansione.', 1002),
  ('c_occhio', 'Occhio xeno', 'computer', 'sensori', 'xeno', '{"scanner":"holo","scan_range":3}', 160, 'Scanner e raggio di scansione.', 1003),
  ('c_sguardo', 'Sguardo Precursore', 'computer', 'sensori', 'precursor', '{"scanner":"holo","scan_range":4}', 420, 'Scanner e raggio di scansione.', 1004),
  ('c_disturbatore', 'Disturbatore di bordo', 'computer', 'guerra_elettronica', 'civ', '{"ecm_pct":5}', 8, 'Disturbo elettronico: indebolisce i colpi degli NPC e dei caccia schierati.', 1100),
  ('c_contromisure', 'Contromisure elettroniche', 'computer', 'guerra_elettronica', 'mil', '{"ecm_pct":8}', 22, 'Disturbo elettronico: indebolisce i colpi degli NPC e dei caccia schierati.', 1101),
  ('c_gew', 'Guerra elettronica', 'computer', 'guerra_elettronica', 'exp', '{"combat_pct":10,"ecm_pct":12}', 60, 'Disturbo elettronico: indebolisce i colpi degli NPC e dei caccia schierati.', 1102),
  ('c_silenzio', 'Velo di silenzio xeno', 'computer', 'guerra_elettronica', 'xeno', '{"ecm_pct":17,"combat_pct":4}', 160, 'Disturbo elettronico: indebolisce i colpi degli NPC e dei caccia schierati.', 1103),
  ('c_dominatore', 'Dominatore di segnali', 'computer', 'guerra_elettronica', 'precursor', '{"ecm_pct":24,"combat_pct":8}', 420, 'Disturbo elettronico: indebolisce i colpi degli NPC e dei caccia schierati.', 1104),
  ('c_analizzatore', 'Analizzatore di relitti', 'computer', 'analisi', 'civ', '{"drop_luck_pct":6}', 8, 'Fiuto per il bottino: più probabilità di recuperare moduli.', 1200),
  ('c_balistico', 'Calcolatore di recupero', 'computer', 'analisi', 'mil', '{"drop_luck_pct":10}', 22, 'Fiuto per il bottino: più probabilità di recuperare moduli.', 1201),
  ('c_predittore', 'Predittore di bottino', 'computer', 'analisi', 'exp', '{"drop_luck_pct":16}', 60, 'Fiuto per il bottino: più probabilità di recuperare moduli.', 1202),
  ('c_preveggenza', 'Preveggenza xeno', 'computer', 'analisi', 'xeno', '{"drop_luck_pct":25}', 160, 'Fiuto per il bottino: più probabilità di recuperare moduli.', 1203),
  ('c_mente', 'Mente Precursore', 'computer', 'analisi', 'precursor', '{"drop_luck_pct":32,"scan_range":3,"combat_pct":6}', 420, 'Fiuto per il bottino: più probabilità di recuperare moduli.', 1204),
  ('c_transponder', 'Transponder contraffatto', 'computer', 'transponder', 'civ', '{"notoriety_reduce_pct":10}', 8, 'Identità falsificata: i crimini pesano meno sulla notorietà.', 1300),
  ('c_copertura', 'Identità di copertura', 'computer', 'transponder', 'mil', '{"notoriety_reduce_pct":18}', 22, 'Identità falsificata: i crimini pesano meno sulla notorietà.', 1301),
  ('c_mascheratore', 'Mascheratore di firma', 'computer', 'transponder', 'exp', '{"notoriety_reduce_pct":28}', 60, 'Identità falsificata: i crimini pesano meno sulla notorietà.', 1302),
  ('c_camaleonte', 'Firma camaleonte xeno', 'computer', 'transponder', 'xeno', '{"notoriety_reduce_pct":40}', 160, 'Identità falsificata: i crimini pesano meno sulla notorietà.', 1303),
  ('c_ombra', 'Ombra legale Precursore', 'computer', 'transponder', 'precursor', '{"notoriety_reduce_pct":55}', 420, 'Identità falsificata: i crimini pesano meno sulla notorietà.', 1304),
  ('u_stiva', 'Stiva ausiliaria', 'utility', 'stive', 'civ', '{"cargo_bonus":4}', 8, 'Stive in più, oltre quelle dello scafo.', 1400),
  ('u_modulare', 'Stiva modulare', 'utility', 'stive', 'mil', '{"cargo_bonus":8}', 22, 'Stive in più, oltre quelle dello scafo.', 1401),
  ('u_compressione', 'Stiva a compressione', 'utility', 'stive', 'exp', '{"cargo_bonus":14}', 60, 'Stive in più, oltre quelle dello scafo.', 1402),
  ('u_dimensionale', 'Stiva dimensionale xeno', 'utility', 'stive', 'xeno', '{"cargo_bonus":22}', 160, 'Stive in più, oltre quelle dello scafo.', 1403),
  ('u_nanosciame', 'Nanosciame Precursore', 'utility', 'stive', 'precursor', '{"cargo_bonus":32,"shield_regen":40}', 420, 'Stive in più, oltre quelle dello scafo.', 1404),
  ('u_rampino', 'Rampino di recupero', 'utility', 'recupero', 'civ', '{"salvage_bonus_pct":15}', 8, 'Più Leghe da ogni relitto e da ogni nemico abbattuto.', 1500),
  ('u_recuperatore', 'Braccio recuperatore', 'utility', 'recupero', 'mil', '{"salvage_bonus_pct":35}', 22, 'Più Leghe da ogni relitto e da ogni nemico abbattuto.', 1501),
  ('u_scomposizione', 'Scompositore rapido', 'utility', 'recupero', 'exp', '{"salvage_bonus_pct":50}', 60, 'Più Leghe da ogni relitto e da ogni nemico abbattuto.', 1502),
  ('u_drone', 'Drone d\'officina', 'utility', 'recupero', 'xeno', '{"salvage_bonus_pct":60,"drop_luck_pct":8}', 160, 'Più Leghe da ogni relitto e da ogni nemico abbattuto.', 1503),
  ('u_sciame', 'Sciame di recupero Precursore', 'utility', 'recupero', 'precursor', '{"salvage_bonus_pct":80,"drop_luck_pct":10}', 420, 'Più Leghe da ogni relitto e da ogni nemico abbattuto.', 1504),
  ('u_mantello', 'Generatore di mantello', 'utility', 'occultamento', 'exp', '{"cloak":1}', 60, 'Dispositivo di occultamento: i modelli più rari aiutano anche a sfuggire agli agganci.', 1602),
  ('u_mantello_xeno', 'Mantello xeno', 'utility', 'occultamento', 'xeno', '{"cloak":1,"evade_pct":10}', 160, 'Dispositivo di occultamento: i modelli più rari aiutano anche a sfuggire agli agganci.', 1603),
  ('u_velo', 'Velo di Precursore', 'utility', 'occultamento', 'precursor', '{"cloak":1,"evade_pct":18}', 420, 'Dispositivo di occultamento: i modelli più rari aiutano anche a sfuggire agli agganci.', 1604),
  ('u_officina', 'Officina di bordo', 'utility', 'officina', 'civ', '{"fighter_regen":40}', 8, 'Fabbrica caccia a bordo: ne produce ogni ora, fino al tetto della nave.', 1700),
  ('u_catena', 'Catena di montaggio caccia', 'utility', 'officina', 'mil', '{"fighter_regen":100}', 22, 'Fabbrica caccia a bordo: ne produce ogni ora, fino al tetto della nave.', 1701),
  ('u_forgia', 'Forgia automatica', 'utility', 'officina', 'exp', '{"fighter_regen":220}', 60, 'Fabbrica caccia a bordo: ne produce ogni ora, fino al tetto della nave.', 1702),
  ('u_nido', 'Nido riproduttivo xeno', 'utility', 'officina', 'xeno', '{"fighter_regen":400}', 160, 'Fabbrica caccia a bordo: ne produce ogni ora, fino al tetto della nave.', 1703),
  ('u_fabbrica', 'Fabbrica Precursore', 'utility', 'officina', 'precursor', '{"fighter_regen":700}', 420, 'Fabbrica caccia a bordo: ne produce ogni ora, fino al tetto della nave.', 1704)
ON DUPLICATE KEY UPDATE name = VALUES(name), category = VALUES(category), family = VALUES(family),
  rarity = VALUES(rarity), effects = VALUES(effects), base_salvage = VALUES(base_salvage),
  descr = IF(descr IS NULL OR descr = '', VALUES(descr), descr), sort_order = VALUES(sort_order);
